"$schema" = 'https://starship.rs/config-schema.json'

# layout
format = """
$username\
$directory\
$git_branch\
$git_status\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
$lua\
$docker_context\
$character"""

# right aligned
right_format = '$cmd_duration'

add_newline = false
scan_timeout = 10

# username
[username]
show_always = true
style_user = "bold #bcbcbc"
style_root = "#ff2e3f"
format = '[$user ]($style)'

# directory
[directory]
style = "bold #009fff"
format = '[$path]($style) '
truncation_length = 3
truncation_symbol = '…/'

# git branch
[git_branch]
style = "italic #08c0ef"
format = '[$branch ]($style)'

# git status
[git_status]
style = "#08c0ef"
format = '[($all_status$ahead_behind )]($style)'

# languages
[c]
symbol = ""
style = "dimmed"
format = '[$symbol( $version)]($style) '

[rust]
symbol = ""
style = "dimmed"
format = '[$symbol( $version)]($style) '

[golang]
symbol = "󰟓"
style = "dimmed"
format = '[$symbol( $version)]($style) '

[nodejs]
symbol = "󰎙"
style = "dimmed"
format = '[$symbol( $version)]($style) '

[php]
symbol = "󰌟"
style = "dimmed"
format = '[$symbol( $version)]($style) '

[java]
symbol = ""
style = "dimmed"
format = '[$symbol( $version)]($style) '

[kotlin]
symbol = ""
style = "dimmed"
format = '[$symbol( $version)]($style) '

[haskell]
symbol = ""
style = "dimmed"
format = '[$symbol( $version)]($style) '

[python]
symbol = ""
style = "dimmed"
format = '[$symbol( $version)]($style) '

[lua]
symbol = "󰢱"
style = "dimmed"
format = '[$symbol( $version)]($style) '

# docker
[docker_context]
symbol = "󰡨"
style = "dimmed"
format = '[$symbol$context]($style) '

# character
[character]
success_symbol  = '[](#009fff)'
error_symbol = '[](#ff2e3f)'

# command duration
[cmd_duration]
min_time = 2000
format = '[ $duration ](dimmed)'
show_milliseconds = false
