"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$directory\
$git_branch\
$git_status\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
$lua\
$docker_context\
$character"""

add_newline = false

# username
[username]
show_always = true
style_user = "bright-yellow"
style_root = "purple"
format = '[$user ]($style)'

# directory
[directory]
style = "blue"
format = '[$path]($style) '
truncation_length = 3
truncation_symbol = "…/"

# git branch
[git_branch]
style = "bright-blue"
format = '[$branch ]($style)'

# git status
[git_status]
style = "bright-blue"
format = '[($all_status$ahead_behind )]($style)'

# nodejs
[nodejs]
symbol = "󰎙"
style = "bright-green"
format = '[$symbol( $version)]($style) '

# c
[c]
symbol = ""
style = "white"
format = '[$symbol( $version)]($style) '

# rust
[rust]
symbol = ""
style = "red"
format = '[$symbol( $version)]($style) '

# go
[golang]
symbol = "󰟓"
style = "cyan"
format = '[$symbol( $version)]($style) '

# php
[php]
symbol = "󰌟"
style = "purple"
format = '[$symbol( $version)]($style) '

# java
[java]
symbol = ""
style = "yellow"
format = '[$symbol( $version)]($style) '

# kotlin
[kotlin]
symbol = ""
style = "bright-purple"
format = '[$symbol( $version)]($style) '

# haskell
[haskell]
symbol = ""
style = "magenta"
format = '[$symbol( $version)]($style) '

# python
[python]
symbol = ""
style = "bright-yellow"
format = '[$symbol( $version)]($style) '

# lua
[lua]
symbol = "󰢱"
style = "bright-yellow"
format = '[$symbol( $version)]($style) '

# docker
[docker_context]
symbol = "󰡨"
style = "blue"
format = '[$symbol$context]($style) '

# line break 
[line_break]
disabled = true

# character
[character]
format = "[](bright-blue) "
